package Plugins.ExamPaperServiceApi

import Plugins.ExamPaperServiceApi.MSAkkaExamPaperServiceMessageExtended
import Plugins.ExamPaperServiceShared.SimpleExamPaper

case class getAllExamPaper(
) extends MSAkkaExamPaperServiceMessageExtended[Array[SimpleExamPaper]]
