interface Window {
    userType: string
    isEnglish: boolean
    isBarOpen: boolean
    isLogged: boolean
    userName: string
    isBlocked: boolean
    currentPaperIndex: number
    currentAnswerIndex: number
    currentEditingPaperIndex: number
    currentExamName: string
    currentExamYear: string
    password: string
    realName: string
    gender: string
    ID: string
    phoneNumber: string
    provinceFrom: string
    CEEScore: string
    CEERanking: string
    awards: string
    selfIntroduction: string
    mesTitle: string
    mesContent: string
    mesRank: number
    mesStatus: Array<string>
    mesType: string
    mesDate: string
    currentStartTime: string
    currentEndTime: string
    tarName: string
    flag: boolean
}